version: '3.1.2'
services:
    spring_boot_com_mysql:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: spring_boot_com_mysql/api
        ports: 
            - '5005:5005'
            - '5005:5005'
        environment:
            - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
            - PROFILE=dev
        links: 
            - db
    db:
        image: mysql:5.7.42
        ports:
            - '3306:3306'
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_DATABASE=spring_boot_mysql
            - MYSQL_USER=ifsul
            - MYSQL_PASSWORD=4A3B2C
            - MYSQL_ROOT_PASSWORD=4A3B2C
        volumes:
            - ./docker/volume_mysql:/var/lib/mysql
